name: Make release tag latest

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup registry
        run: |
          npm config set registry https://artifactory.infrateam.xyz/artifactory/api/npm/npm/
          npm config set always-auth true
          echo "//https://artifactory.infrateam.xyz/artifactory/api/npm/npm/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - uses: ./.github/actions/makeLatest
        name: Get release tag
        id: getReleaseTag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Make dist-tag latest
        if: steps.getReleaseTag.outputs.version
        run: |
          npm dist-tag add ${{ steps.getReleaseTag.outputs.packageName }}@${{ steps.getReleaseTag.outputs.version }} latest
